/**
 * Issue #311: Hunch's appended hook blocks must never be written where they are
 * dead (pre-commit framework `exec`, husky v9 `.husky/_/h` → `exit $c`, any
 * trailing exec/exit) or where they would commit this machine's CLI path
 * (husky ≤8 / tracked core.hooksPath). Every fixture is a fresh temp repo —
 * never a real checkout or worktree (con_38bf8aa397).
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync, readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync, realpathSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFileSync, spawnSync } from "node:child_process";
import {
  installPostCommitHook, installPreCommitHook, installPostMergeHook, installPostCheckoutHook,
  hookStatus, hookReport, formatHookInstall, terminalExitLine, PORTABLE_HOOK_INVOCATION,
} from "../src/integrations/hooks.js";

const PROJECT_ROOT = process.cwd();
const TSX = join(PROJECT_ROOT, "node_modules/tsx/dist/cli.mjs");
const CLI = join(PROJECT_ROOT, "src/cli/index.ts");
// A machine-local invocation carrying this machine's absolute paths — exactly
// what must never land in a tracked file.
const LOCAL_INV = `${JSON.stringify(process.execPath)} ${JSON.stringify(CLI)}`;

function git(root: string, ...args: string[]): string {
  return execFileSync("git", args, { cwd: root, encoding: "utf8", env: { ...process.env, GIT_CONFIG_NOSYSTEM: "1" }, stdio: ["ignore", "pipe", "pipe"] }).trim();
}

function repo(prefix = "hunch-hookmgr-"): string {
  const r = realpathSync.native(mkdtempSync(join(tmpdir(), prefix)));
  git(r, "init", "-q", "-b", "main");
  git(r, "config", "user.email", "hooks@test.invalid");
  git(r, "config", "user.name", "Hook Managers");
  git(r, "config", "commit.gpgsign", "false");
  return r;
}

function preCommitFrameworkHook(hookType: string): string {
  return [
    "#!/usr/bin/env bash",
    "# File generated by pre-commit: https://pre-commit.com",
    "# ID: 138fd403232d2ddd5efb44317e38bf03",
    "",
    "# start templated",
    "INSTALL_PYTHON=/usr/bin/python3",
    `ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=${hookType})`,
    "# end templated",
    "",
    'HERE="$(cd "$(dirname "$0")" && pwd)"',
    'ARGS+=(--hook-dir "$HERE" -- "$@")',
    "",
    'if [ -x "$INSTALL_PYTHON" ]; then',
    '    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"',
    "elif command -v pre-commit > /dev/null; then",
    '    exec pre-commit "${ARGS[@]}"',
    "else",
    "    echo '`pre-commit` not found.  Did you install it into your venv?' 1>&2",
    "    exit 1",
    "fi",
    "",
  ].join("\n");
}

const HUSKY_H = [
  "#!/usr/bin/env sh",
  '[ "$HUSKY" = "2" ] && set -x',
  'n=$(basename "$0")',
  's=$(dirname "$(dirname "$0")")/$n',
  "",
  '[ ! -f "$s" ] && exit 0',
  "",
  'i="${XDG_CONFIG_HOME:-$HOME/.config}/husky/init.sh"',
  '[ -f "$i" ] && . "$i"',
  "",
  '[ "${HUSKY-}" = "0" ] && exit 0',
  "",
  'export PATH="node_modules/.bin:$PATH"',
  'sh -e "$s" "$@"',
  "c=$?",
  "",
  '[ $c != 0 ] && echo "husky - $n script failed (code $c)"',
  '[ $c = 127 ] && echo "husky - command not found in PATH=$PATH"',
  "exit $c",
  "",
].join("\n");
const HUSKY_STUB = '#!/usr/bin/env sh\n. "${0%/*}/h"\n';

function huskyV9(r: string): void {
  mkdirSync(join(r, ".husky", "_"), { recursive: true });
  writeFileSync(join(r, ".husky", "_", ".gitignore"), "*\n");
  writeFileSync(join(r, ".husky", "_", "h"), HUSKY_H);
  for (const name of ["pre-commit", "post-commit", "post-merge", "post-checkout"]) writeFileSync(join(r, ".husky", "_", name), HUSKY_STUB);
  writeFileSync(join(r, ".husky", "pre-commit"), "npm test\n");
  git(r, "config", "core.hooksPath", ".husky/_");
}

function allFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((n) => {
    const p = join(dir, n);
    return statSync(p).isDirectory() ? allFiles(p) : [p];
  });
}

test("terminalExitLine: unconditional exec/exit and all-branch if/else exits are terminal; conditional exits are not", () => {
  assert.ok(terminalExitLine(preCommitFrameworkHook("pre-commit")));
  assert.equal(terminalExitLine("#!/bin/sh\nnpm test\nexit 0\n"), "exit 0");
  assert.equal(terminalExitLine("#!/bin/sh\nexec lint-staged\n"), "exec lint-staged");
  assert.equal(terminalExitLine(HUSKY_H), "exit $c");
  assert.equal(terminalExitLine("#!/bin/sh\n[ -f x ] || exit 0\necho ok\n"), null);
  assert.equal(terminalExitLine("#!/bin/sh\nif [ -z \"$X\" ]; then\n  exit 1\nfi\necho ok\n"), null);
  assert.equal(terminalExitLine("#!/bin/sh\nif [ -z \"$X\" ]; then\n  exit 1\nfi\n"), null, "no else branch: falls through");
  assert.equal(terminalExitLine("#!/bin/sh\necho user-hook\n"), null);
  assert.equal(terminalExitLine("#!/bin/sh\nfail() {\nexit 1\n}\nnpm test || fail\n"), null, "exit inside an unindented function body");
  assert.equal(terminalExitLine("#!/bin/sh\nif [ -n \"$SKIP\" ]; then\nexit 0\nfi\nnpm test\n"), null, "exit inside an unindented if");
  assert.equal(terminalExitLine("#!/bin/sh\nif [ -n \"$SKIP\" ]; then exit 0; fi\n  exec ./next-hook\n"), "exec ./next-hook", "one-line if closes; indented top-level exec is terminal");
  assert.equal(terminalExitLine("#!/bin/sh\nfor f in a b; do\n  echo $f\ndone\nexit 0\n"), "exit 0");
});

test("pre-commit framework: install writes nothing, returns a repo: local snippet, and status is not installed", () => {
  const r = repo();
  try {
    const hookPath = join(r, ".git", "hooks", "pre-commit");
    const generated = preCommitFrameworkHook("pre-commit");
    writeFileSync(hookPath, generated);
    const res = installPreCommitHook(r, LOCAL_INV);
    assert.equal(res.action, "managed-elsewhere");
    assert.equal(res.manager, "pre-commit");
    assert.equal(readFileSync(hookPath, "utf8"), generated, "the generated hook is untouched");
    assert.equal(res.path, join(r, ".pre-commit-config.yaml"));
    assert.match(res.snippet ?? "", /- repo: local/);
    assert.match(res.snippet ?? "", /id: hunch-pre-commit/);
    assert.match(res.snippet ?? "", /stages: \[pre-commit\]/);
    assert.ok((res.snippet ?? "").includes(PORTABLE_HOOK_INVOCATION));
    assert.ok(!(res.snippet ?? "").includes(process.execPath), "tracked config never gets this machine's node path");
    assert.equal(existsSync(join(r, ".pre-commit-config.yaml")), false, "Hunch never edits the manager's config itself");
    assert.equal(hookReport(r).preCommit.state, "missing");

    // The user adds the snippet: now it's installed, and a re-run is a no-op.
    writeFileSync(join(r, ".pre-commit-config.yaml"), `repos:\n${res.snippet}\n`);
    assert.equal(hookReport(r).preCommit.state, "installed");
    assert.equal(hookStatus(r).preCommit, true);
    assert.equal(installPreCommitHook(r, LOCAL_INV).action, "unchanged");
    assert.equal(readFileSync(hookPath, "utf8"), generated);
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("pre-commit framework: post-checkout snippet reads the checkout type from pre-commit's env, not $3", () => {
  const r = repo();
  try {
    writeFileSync(join(r, ".git", "hooks", "post-checkout"), preCommitFrameworkHook("post-checkout"));
    const res = installPostCheckoutHook(r, LOCAL_INV);
    assert.equal(res.action, "managed-elsewhere");
    assert.match(res.snippet ?? "", /PRE_COMMIT_CHECKOUT_TYPE/);
    assert.doesNotMatch(res.snippet ?? "", /\\"\$3\\"/);
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("pre-commit framework: a Hunch block previously appended after its exec is reported installed-but-unreachable (hookStatus + doctor)", () => {
  const r = repo();
  try {
    writeFileSync(join(r, "app.ts"), "export const x = 1;\n");
    git(r, "add", "-A");
    git(r, "commit", "-qm", "init");
    // Old Hunch appended after the generated hook's exec.
    const hookPath = join(r, ".git", "hooks", "post-commit");
    writeFileSync(hookPath, `${preCommitFrameworkHook("post-commit")}# >>> hunch post-commit >>>\nhunch sync --from-hook\n# <<< hunch post-commit <<<\n`);
    installPostMergeHook(r, "hunch");
    const report = hookReport(r);
    assert.equal(report.postCommit.state, "unreachable");
    assert.equal(report.postCommit.manager, "pre-commit");
    assert.equal(hookStatus(r).postCommit, false, "an unreachable block is not installed");
    assert.equal(installPostCommitHook(r, "hunch").action, "managed-elsewhere");

    const run = spawnSync(process.execPath, [TSX, CLI, "doctor"], {
      cwd: r,
      env: { ...process.env, HUNCH_PRIVATE_DIR: "", HUNCH_SYNTH_PROVIDER: "deterministic", NO_COLOR: "1" },
      encoding: "utf8",
    });
    const out = `${run.stdout}${run.stderr}`;
    assert.match(out, /hooks:.*installed but unreachable: post-commit/s);
    assert.doesNotMatch(out, /hooks:\s+post-commit, post-merge installed/);
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("pre-commit framework migration mode: a reachable block in <hook>.legacy counts as installed", () => {
  const r = repo();
  try {
    writeFileSync(join(r, ".git", "hooks", "post-commit"), preCommitFrameworkHook("post-commit"));
    writeFileSync(join(r, ".git", "hooks", "post-commit.legacy"), "#!/bin/sh\n# >>> hunch post-commit >>>\nhunch sync --from-hook --quiet\n# <<< hunch post-commit <<<\n");
    assert.equal(hookReport(r).postCommit.state, "installed");
    assert.equal(installPostCommitHook(r, "hunch").action, "unchanged");
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("husky v9: nothing is appended to .husky/_ (dead after exit $c, regenerated on install); snippet targets .husky/<hook>", () => {
  const r = repo();
  try {
    huskyV9(r);
    const before = Object.fromEntries(allFiles(join(r, ".husky")).map((p) => [p, readFileSync(p, "utf8")]));
    const results = [
      installPostCommitHook(r, LOCAL_INV),
      installPreCommitHook(r, LOCAL_INV),
      installPostMergeHook(r, LOCAL_INV),
      installPostCheckoutHook(r, LOCAL_INV),
    ];
    const after = Object.fromEntries(allFiles(join(r, ".husky")).map((p) => [p, readFileSync(p, "utf8")]));
    assert.deepEqual(after, before, "no husky file created or modified");
    for (const res of results) {
      assert.equal(res.action, "managed-elsewhere");
      assert.equal(res.manager, "husky");
      assert.ok(res.snippet?.includes(PORTABLE_HOOK_INVOCATION));
      assert.ok(!res.snippet?.includes(process.execPath), "husky scripts are tracked — no absolute node path");
    }
    assert.equal(results[0]!.path, join(r, ".husky", "post-commit"));
    // post-merge carries BOTH managed blocks in one snippet.
    assert.match(results[2]!.snippet ?? "", /# >>> hunch post-merge >>>/);
    assert.match(results[2]!.snippet ?? "", /# >>> hunch post-merge \(repair-provenance\) >>>/);
    assert.deepEqual(hookStatus(r), { postCommit: false, preCommit: false, postMerge: false, postCheckout: false });

    // CLI rendering surfaces the reason and the snippet.
    const lines = formatHookInstall(r, "post-commit hook", results[0]!, " (learning loop)").join("\n");
    assert.match(lines, /⚠ post-commit hook NOT installed — husky v9/);
    assert.match(lines, /add this to \.husky\/post-commit yourself/);

    // The user adds the snippets to husky's own scripts → installed, re-run unchanged.
    writeFileSync(join(r, ".husky", "post-commit"), `${results[0]!.snippet}\n`);
    writeFileSync(join(r, ".husky", "post-merge"), `${results[2]!.snippet}\n`);
    assert.equal(hookStatus(r).postCommit, true);
    assert.equal(hookStatus(r).postMerge, true);
    assert.equal(installPostCommitHook(r, LOCAL_INV).action, "unchanged");
    assert.equal(installPostMergeHook(r, LOCAL_INV).action, "unchanged");
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("husky v9: a reachable block in husky's own script whose launcher is gone is stale, and the install says to replace it", () => {
  const r = repo();
  try {
    huskyV9(r);
    // Reachable (husky's own script), but the absolute launcher it points at is
    // gone after a reinstall — never executed here, only read.
    const dead = join(r, "gone", "bin", "hunch");
    writeFileSync(join(r, ".husky", "post-commit"), `# >>> hunch post-commit >>>\n${dead} sync --from-hook --quiet\n# <<< hunch post-commit <<<\n`);
    const report = hookReport(r);
    assert.equal(report.postCommit.state, "stale");
    assert.equal(hookStatus(r).postCommit, false);

    const res = installPostCommitHook(r, "hunch");
    assert.equal(res.action, "managed-elsewhere");
    assert.match(res.reason ?? "", /stale/, "a stale block must not be reported as 'a hook manager owns this hook'");
    assert.ok(res.snippet?.includes(PORTABLE_HOOK_INVOCATION));
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("husky v9: a block in husky's own script run through a package runner is installed, and re-installing leaves it alone", () => {
  const r = repo();
  try {
    huskyV9(r);
    writeFileSync(join(r, ".husky", "post-commit"), "# >>> hunch post-commit >>>\npnpm exec hunch sync --from-hook --quiet\n# <<< hunch post-commit <<<\n");
    assert.equal(hookReport(r).postCommit.state, "installed");
    assert.equal(hookStatus(r).postCommit, true);
    assert.equal(installPostCommitHook(r, "hunch").action, "unchanged");
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("husky v9: a block an older Hunch appended into .husky/_/<hook> is reported unreachable", () => {
  const r = repo();
  try {
    huskyV9(r);
    writeFileSync(join(r, ".husky", "_", "post-commit"), `${HUSKY_STUB}# >>> hunch post-commit >>>\nhunch sync\n# <<< hunch post-commit <<<\n`);
    const report = hookReport(r);
    assert.equal(report.postCommit.state, "unreachable");
    assert.equal(report.postCommit.manager, "husky");
    assert.equal(hookStatus(r).postCommit, false);
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("husky v9: hunch init reports the hooks as NOT installed with the snippet, and writes nothing under .husky", { timeout: 120_000 }, () => {
  const r = repo();
  try {
    writeFileSync(join(r, "app.ts"), "export const x = 1;\n");
    git(r, "add", "app.ts");
    git(r, "commit", "-qm", "init");
    huskyV9(r);
    const before = Object.fromEntries(allFiles(join(r, ".husky")).map((p) => [p, readFileSync(p, "utf8")]));
    const run = spawnSync(process.execPath, [TSX, CLI, "init", "--no-index", "--no-providers", "--no-agent-hooks"], {
      cwd: r,
      env: { ...process.env, HUNCH_PRIVATE_DIR: "", HUNCH_SYNTH_PROVIDER: "deterministic", NO_COLOR: "1" },
      encoding: "utf8",
    });
    const out = `${run.stdout}${run.stderr}`;
    assert.equal(run.status, 0, out);
    assert.match(out, /⚠ post-commit hook NOT installed/);
    assert.match(out, /⚠ pre-commit constraint guard NOT installed/);
    assert.doesNotMatch(out, /✓ post-commit hook/);
    assert.ok(out.includes(PORTABLE_HOOK_INVOCATION));
    const after = Object.fromEntries(allFiles(join(r, ".husky")).map((p) => [p, readFileSync(p, "utf8")]));
    assert.deepEqual(after, before);
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("husky ≤8 (core.hooksPath=.husky, tracked): nothing with an absolute path is written into the committed hooks dir", () => {
  const r = repo();
  try {
    mkdirSync(join(r, ".husky", "_"), { recursive: true });
    writeFileSync(join(r, ".husky", "_", ".gitignore"), "*\n");
    writeFileSync(join(r, ".husky", "_", "husky.sh"), "#!/usr/bin/env sh\n# husky\n");
    const userHook = '#!/usr/bin/env sh\n. "$(dirname -- "$0")/_/husky.sh"\n\nnpm test\n';
    writeFileSync(join(r, ".husky", "pre-commit"), userHook);
    git(r, "add", ".husky/pre-commit");
    git(r, "commit", "-qm", "husky");
    git(r, "config", "core.hooksPath", ".husky");

    const results = [
      installPostCommitHook(r, LOCAL_INV),
      installPreCommitHook(r, LOCAL_INV),
      installPostMergeHook(r, LOCAL_INV),
      installPostCheckoutHook(r, LOCAL_INV),
    ];
    for (const res of results) {
      assert.equal(res.action, "managed-elsewhere");
      assert.equal(res.manager, "husky-legacy");
      assert.ok(!res.snippet?.includes(process.execPath));
    }
    assert.equal(readFileSync(join(r, ".husky", "pre-commit"), "utf8"), userHook);
    for (const file of allFiles(join(r, ".husky"))) {
      const text = readFileSync(file, "utf8");
      assert.ok(!text.includes(process.execPath), `${file} must not carry this machine's node path`);
      assert.doesNotMatch(text, /# >>> hunch/, `${file} must not get a hunch block`);
    }
    assert.equal(existsSync(join(r, ".husky", "post-commit")), false);
    assert.equal(git(r, "status", "--porcelain"), "", "the work tree stays clean");
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("an untracked but committable core.hooksPath inside the work tree is treated as tracked", () => {
  const r = repo();
  try {
    git(r, "config", "core.hooksPath", ".githooks");
    const res = installPostCommitHook(r, LOCAL_INV);
    assert.equal(res.action, "managed-elsewhere");
    assert.equal(res.manager, "tracked-hooks-path");
    assert.equal(existsSync(join(r, ".githooks", "post-commit")), false);
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("plain .git/hooks whose existing hook ends in exit: nothing appended, unreachable result with a placement snippet", () => {
  const r = repo();
  try {
    const hookPath = join(r, ".git", "hooks", "post-commit");
    const existing = "#!/bin/sh\nnpm run notify\nexit 0\n";
    writeFileSync(hookPath, existing);
    const res = installPostCommitHook(r, "hunch");
    assert.equal(res.action, "unreachable");
    assert.equal(res.manager, "exec-exit");
    assert.equal(readFileSync(hookPath, "utf8"), existing);
    assert.match(res.snippet ?? "", /insert ABOVE the final exec\/exit/);
    assert.match(res.snippet ?? "", /hunch sync --from-hook --quiet/, "local .git/hooks keeps the local invocation");
    assert.equal(hookReport(r).postCommit.state, "missing");
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("plain .git/hooks: an existing Hunch block after exec is unreachable; one before the exit is installed and still updates in place", () => {
  const r = repo();
  try {
    const hookPath = join(r, ".git", "hooks", "post-commit");
    writeFileSync(hookPath, "#!/bin/sh\nexec ./other-hook\n# >>> hunch post-commit >>>\nhunch sync --from-hook --quiet\n# <<< hunch post-commit <<<\n");
    assert.equal(hookReport(r).postCommit.state, "unreachable");
    assert.equal(hookStatus(r).postCommit, false);
    assert.equal(installPostCommitHook(r, "hunch").action, "unreachable");

    // An older (but still working) invocation before the exit: reachable, live, updated in place.
    writeFileSync(hookPath, "#!/bin/sh\n# >>> hunch post-commit >>>\nhunch sync --from-hook\n# <<< hunch post-commit <<<\nexit 0\n");
    assert.equal(hookReport(r).postCommit.state, "installed");
    assert.equal(installPostCommitHook(r, "hunch").action, "updated");
    const text = readFileSync(hookPath, "utf8");
    assert.match(text, /hunch sync --from-hook --quiet/);
    assert.match(text, /# <<< hunch post-commit <<<\nexit 0\n$/);
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("plain repo without a hook manager: behavior unchanged (created, appended, unchanged, installed)", () => {
  const r = repo();
  try {
    assert.equal(installPostCommitHook(r, "hunch").action, "created");
    assert.equal(installPostCommitHook(r, "hunch").action, "unchanged");
    writeFileSync(join(r, ".git", "hooks", "post-merge"), "#!/bin/sh\necho user-hook\n");
    const pm = installPostMergeHook(r, "hunch");
    assert.equal(pm.action, "appended");
    assert.equal(pm.manager, undefined);
    assert.deepEqual(hookStatus(r), { postCommit: true, preCommit: false, postMerge: true, postCheckout: false });
    assert.equal(hookReport(r).postMerge.state, "installed");
    assert.deepEqual(formatHookInstall(r, "post-merge hook", pm, " (x)"), ["  ✓ post-merge hook appended (x)"]);
  } finally { rmSync(r, { recursive: true, force: true }); }
});

test("linked worktree of a temp repo: the shared hooks dir in the common git dir is still a plain install", () => {
  const r = repo();
  const wt = `${r}-wt`;
  try {
    writeFileSync(join(r, "a.txt"), "a\n");
    git(r, "add", "a.txt");
    git(r, "commit", "-qm", "init");
    git(r, "worktree", "add", "-q", wt, "-b", "side");
    const res = installPostCommitHook(wt, "hunch");
    assert.equal(res.action, "created");
    assert.ok(existsSync(join(r, ".git", "hooks", "post-commit")));
    assert.equal(hookStatus(wt).postCommit, true);
  } finally {
    rmSync(wt, { recursive: true, force: true });
    rmSync(r, { recursive: true, force: true });
  }
});
