# Generated by tooling/generate-state-contracts.mjs; do not edit.
# Types describe wire shapes; semantic validation remains server-owned.
from typing import Any, Literal, Required, TypedDict, TypeAlias

Scope = TypedDict("Scope", {
    "kind": Required[Literal["organization", "team", "user", "repository"]],
    "id": Required[str],
}, total=False)

ExternalRef = TypedDict("ExternalRef", {
    "system": Required[str],
    "object_type": Required[str],
    "object_key": Required[str],
    "version": str,
    "content_hash": str,
    "observed_at": Required[str],
    "locator": str,
}, total=False)

DependencyRef1Scope = TypedDict("DependencyRef1Scope", {
    "kind": Required[Literal["organization", "team", "user", "repository"]],
    "id": Required[str],
}, total=False)

DependencyRef1 = TypedDict("DependencyRef1", {
    "kind": Required[Literal["record"]],
    "id": Required[str],
    "record_hash": Required[str],
    "scope": DependencyRef1Scope,
}, total=False)

DependencyRef2Ref = TypedDict("DependencyRef2Ref", {
    "system": Required[str],
    "object_type": Required[str],
    "object_key": Required[str],
    "version": str,
    "content_hash": str,
    "observed_at": Required[str],
    "locator": str,
}, total=False)

DependencyRef2 = TypedDict("DependencyRef2", {
    "kind": Required[Literal["external"]],
    "ref": Required[DependencyRef2Ref],
}, total=False)

DependencyRef3 = TypedDict("DependencyRef3", {
    "kind": Required[Literal["schema"]],
    "name": Required[str],
    "fingerprint": Required[str],
}, total=False)

DependencyRef: TypeAlias = DependencyRef1 | DependencyRef2 | DependencyRef3

ActionReceiptVisibility = TypedDict("ActionReceiptVisibility", {
    "owner": Required[str],
    "readers": Required[list[str]],
    "writers": Required[list[str]],
}, total=False)

ActionReceiptProvenance = TypedDict("ActionReceiptProvenance", {
    "source": Required[str],
    "confidence": Required[float],
    "evidence": Required[list[str]],
    "last_verified": str,
}, total=False)

ActionReceipt = TypedDict("ActionReceipt", {
    "visibility": ActionReceiptVisibility,
    "schema": Required[Literal["nuryel.receipt/1"]],
    "id": Required[str],
    "scope": Required[DependencyRef1Scope],
    "actor": Required[str],
    "action_kind": Required[str],
    "target": Required[DependencyRef2Ref],
    "request_fingerprint": Required[str],
    "idempotency_key": str,
    "state": Required[Literal["requested", "succeeded", "failed", "unknown", "verified"]],
    "occurred_at": Required[str],
    "verified_at": str,
    "result_fingerprint": str,
    "invalidates": Required[list[str]],
    "rests_on": list[DependencyRef1 | DependencyRef2 | DependencyRef3],
    "provenance": Required[ActionReceiptProvenance],
}, total=False)

Commitment = TypedDict("Commitment", {
    "visibility": ActionReceiptVisibility,
    "schema": Required[Literal["nuryel.commitment/1"]],
    "id": Required[str],
    "scope": Required[DependencyRef1Scope],
    "subject": Required[str],
    "title": Required[str],
    "owner": Required[str],
    "due": Required[str],
    "status": Required[Literal["open", "waiting", "done", "cancelled"]],
    "source": DependencyRef2Ref,
    "evidence_excerpt": str,
    "closed_by": str,
    "valid_from": Required[str],
    "valid_to": Required[str | None],
    "provenance": Required[ActionReceiptProvenance],
}, total=False)

DerivedStateFieldProvenanceItemSelector1 = TypedDict("DerivedStateFieldProvenanceItemSelector1", {
    "kind": Required[Literal["json_pointer"]],
    "path": Required[str],
}, total=False)

DerivedStateFieldProvenanceItemSelector2 = TypedDict("DerivedStateFieldProvenanceItemSelector2", {
    "kind": Required[Literal["text"]],
    "start": Required[int],
    "end": Required[int],
}, total=False)

DerivedStateFieldProvenanceItem = TypedDict("DerivedStateFieldProvenanceItem", {
    "selector": Required[DerivedStateFieldProvenanceItemSelector1 | DerivedStateFieldProvenanceItemSelector2],
    "value_hash": Required[str],
    "dependency_hashes": Required[list[str]],
}, total=False)

DerivedStateReviewEvidenceItem = TypedDict("DerivedStateReviewEvidenceItem", {
    "ref": Required[DependencyRef2Ref],
    "excerpt": Required[str],
}, total=False)

DerivedStateReview = TypedDict("DerivedStateReview", {
    "by": Required[str],
    "at": Required[str],
    "previous_hash": Required[str],
    "reason": Required[str],
    "evidence": Required[list[DerivedStateReviewEvidenceItem]],
}, total=False)

DerivedState = TypedDict("DerivedState", {
    "visibility": ActionReceiptVisibility,
    "schema": Required[Literal["nuryel.derived/1"]],
    "id": Required[str],
    "scope": Required[DependencyRef1Scope],
    "subject": Required[str],
    "content": Required[str],
    "content_hash": Required[str],
    "dependencies": Required[list[DependencyRef1 | DependencyRef2 | DependencyRef3]],
    "field_provenance": list[DerivedStateFieldProvenanceItem],
    "transform_version": Required[str],
    "computed_at": Required[str],
    "valid_to": Required[str | None],
    "state": Required[Literal["current", "stale", "unknown"]],
    "review": DerivedStateReview,
    "provenance": Required[ActionReceiptProvenance],
}, total=False)

Convention = TypedDict("Convention", {
    "schema": Required[Literal["nuryel.convention/1"]],
    "id": Required[str],
    "scope": Required[DependencyRef1Scope],
    "key": Required[str],
    "value": Required[str],
    "status": Required[Literal["proposed", "accepted", "stale", "withdrawn"]],
    "sources": Required[list[DependencyRef1 | DependencyRef2 | DependencyRef3]],
    "valid_from": Required[str],
    "valid_to": Required[str | None],
    "review_by": Required[str],
    "provenance": Required[ActionReceiptProvenance],
    "visibility": ActionReceiptVisibility,
}, total=False)

WriteResultConflict1 = TypedDict("WriteResultConflict1", {
    "incumbent_id": Required[str],
    "reason": Required[str],
}, total=False)

WriteResult = TypedDict("WriteResult", {
    "schema": Required[Literal["nuryel.state.write/1"]],
    "record_id": Required[str],
    "record_hash": Required[str],
    "durability": Required[Literal["pushed", "committed", "local"]],
    "outcome": Required[Literal["created", "updated", "replayed", "superseded"]],
    "conflict": Required[WriteResultConflict1 | None],
    "record": dict[str, Any],
}, total=False)

CaptureBatchResultResultsItem1Result = TypedDict("CaptureBatchResultResultsItem1Result", {
    "schema": Required[Literal["nuryel.state.write/1"]],
    "record_id": Required[str],
    "record_hash": Required[str],
    "durability": Required[Literal["pushed", "committed", "local"]],
    "outcome": Required[Literal["created", "updated", "replayed", "superseded"]],
    "conflict": Required[WriteResultConflict1 | None],
    "record": dict[str, Any],
}, total=False)

CaptureBatchResultResultsItem1 = TypedDict("CaptureBatchResultResultsItem1", {
    "index": Required[int],
    "status": Required[Literal["saved"]],
    "result": Required[CaptureBatchResultResultsItem1Result],
}, total=False)

CaptureBatchResultResultsItem2 = TypedDict("CaptureBatchResultResultsItem2", {
    "index": Required[int],
    "status": Required[Literal["refused"]],
    "code": Required[str],
    "message": Required[str],
}, total=False)

CaptureBatchResult = TypedDict("CaptureBatchResult", {
    "schema": Required[Literal["nuryel.state.capture-batch/1"]],
    "results": Required[list[CaptureBatchResultResultsItem1 | CaptureBatchResultResultsItem2]],
    "reviews": list[CaptureBatchResultResultsItem1 | CaptureBatchResultResultsItem2],
}, total=False)

RecordsResponse = TypedDict("RecordsResponse", {
    "schema": Required[Literal["nuryel.state.records/1"]],
    "scope": Required[DependencyRef1Scope],
    "records": Required[dict[str, dict[str, Any]]],
    "facets": Required[dict[str, Literal["decisions", "constraints", "bugs", "findings", "receipts", "commitments", "derived", "entities", "relationships", "conventions"]]],
    "missing": Required[list[str]],
    "denied": Required[list[str]],
}, total=False)

ChangeEventCause1 = TypedDict("ChangeEventCause1", {
    "kind": Required[Literal["receipt"]],
    "receipt_id": Required[str],
}, total=False)

ChangeEventCause3 = TypedDict("ChangeEventCause3", {
    "kind": Required[Literal["write"]],
    "principal": Required[str],
}, total=False)

ChangeEvent = TypedDict("ChangeEvent", {
    "visibility": ActionReceiptVisibility,
    "schema": Required[Literal["nuryel.state.subscribe/1"]],
    "seq": Required[int],
    "at": Required[str],
    "scope": Required[DependencyRef1Scope],
    "facet": Required[Literal["decisions", "constraints", "bugs", "findings", "receipts", "commitments", "derived", "entities", "relationships", "conventions"]],
    "record_id": Required[str],
    "record_hash": Required[str],
    "change": Required[Literal["created", "updated", "superseded", "retired", "invalidated"]],
    "subject": str,
    "invalidates": Required[list[str]],
    "cause": ChangeEventCause1 | DependencyRef2 | ChangeEventCause3,
}, total=False)

ReadRequestObservedPageCursor = TypedDict("ReadRequestObservedPageCursor", {
    "snapshot_hash": Required[str],
    "offset": Required[int],
}, total=False)

ReadRequestObservedPage = TypedDict("ReadRequestObservedPage", {
    "cursor": ReadRequestObservedPageCursor,
}, total=False)

ReadRequest = TypedDict("ReadRequest", {
    "scope": Required[DependencyRef1Scope],
    "scopes": list[DependencyRef1Scope],
    "subject": str,
    "task": str,
    "profile": Literal["builder", "reviewer", "architect"],
    "budget_tokens": int,
    "facets": list[Literal["decisions", "constraints", "bugs", "findings", "receipts", "commitments", "derived", "entities", "relationships", "conventions"]],
    "observed_page": ReadRequestObservedPage,
}, total=False)

WriteRequest = TypedDict("WriteRequest", {
    "scope": Required[DependencyRef1Scope],
    "facet": Required[Literal["decisions", "constraints", "bugs", "findings", "receipts", "commitments", "derived", "entities", "relationships", "conventions"]],
    "record": Required[dict[str, Any]],
    "idempotency_key": Required[str],
    "expected_version": str | int | None,
    "supersedes": str,
    "cause": DependencyRef2,
}, total=False)

SubscribeRequest = TypedDict("SubscribeRequest", {
    "scope": Required[DependencyRef1Scope],
    "after_seq": Required[int],
    "subjects": list[str],
    "facets": list[Literal["decisions", "constraints", "bugs", "findings", "receipts", "commitments", "derived", "entities", "relationships", "conventions"]],
}, total=False)

RecordsRequest = TypedDict("RecordsRequest", {
    "scope": Required[DependencyRef1Scope],
    "ids": Required[list[str]],
}, total=False)

CaptureRequestRelevance = TypedDict("CaptureRequestRelevance", {
    "use": Required[Literal["decision", "constraint", "preference", "operational_fact", "ongoing_issue"]],
    "reason": Required[str],
}, total=False)

CaptureRequestEvidenceItem = TypedDict("CaptureRequestEvidenceItem", {
    "ref": Required[DependencyRef2Ref],
    "source_text": Required[str],
    "excerpt": Required[str],
}, total=False)

CaptureRequest = TypedDict("CaptureRequest", {
    "visibility": ActionReceiptVisibility,
    "scope": Required[DependencyRef1Scope],
    "subject": Required[str],
    "statement": Required[str],
    "relevance": Required[CaptureRequestRelevance],
    "evidence": Required[list[CaptureRequestEvidenceItem]],
}, total=False)

CaptureBatchRequestSourcesItem = TypedDict("CaptureBatchRequestSourcesItem", {
    "ref": Required[DependencyRef2Ref],
    "source_text": Required[str],
}, total=False)

CaptureBatchRequestObservationsItemEvidenceItem = TypedDict("CaptureBatchRequestObservationsItemEvidenceItem", {
    "source": Required[int],
    "excerpt": Required[str],
}, total=False)

CaptureBatchRequestObservationsItem = TypedDict("CaptureBatchRequestObservationsItem", {
    "subject": Required[str],
    "statement": Required[str],
    "relevance": Required[CaptureRequestRelevance],
    "visibility": ActionReceiptVisibility,
    "evidence": Required[list[CaptureBatchRequestObservationsItemEvidenceItem]],
}, total=False)

CaptureBatchRequestReviewsItem = TypedDict("CaptureBatchRequestReviewsItem", {
    "record_id": Required[str],
    "expected_hash": Required[str],
    "reason": Required[str],
    "evidence": Required[list[CaptureBatchRequestObservationsItemEvidenceItem]],
}, total=False)

CaptureBatchRequest = TypedDict("CaptureBatchRequest", {
    "scope": Required[DependencyRef1Scope],
    "sources": Required[list[CaptureBatchRequestSourcesItem]],
    "observations": Required[list[CaptureBatchRequestObservationsItem]],
    "reviews": list[CaptureBatchRequestReviewsItem],
}, total=False)

ReadResponseConventionsItemsItemRef = TypedDict("ReadResponseConventionsItemsItemRef", {
    "facet": Required[Literal["decisions", "constraints", "bugs", "findings", "receipts", "commitments", "derived", "entities", "relationships", "conventions"]],
    "id": Required[str],
    "record_hash": Required[str],
    "scope": Required[DependencyRef1Scope],
}, total=False)

ReadResponseConventionsItemsItem = TypedDict("ReadResponseConventionsItemsItem", {
    "ref": Required[ReadResponseConventionsItemsItemRef],
    "key": Required[str],
    "conflict": Required[bool],
    "currentness": Required[Literal["recorded", "stale"]],
}, total=False)

ReadResponseConventions = TypedDict("ReadResponseConventions", {
    "advisory": Required[Literal[True]],
    "items": Required[list[ReadResponseConventionsItemsItem]],
    "truncated": Required[bool],
}, total=False)

ReadResponseStateOfRecord1ObservedPage = TypedDict("ReadResponseStateOfRecord1ObservedPage", {
    "snapshot_hash": Required[str],
    "total": Required[int],
    "next_cursor": Required[ReadRequestObservedPageCursor | None],
}, total=False)

ReadResponseStateOfRecord1 = TypedDict("ReadResponseStateOfRecord1", {
    "subject": Required[str],
    "current": Required[list[ReadResponseConventionsItemsItemRef]],
    "in_force": Required[list[ReadResponseConventionsItemsItemRef]],
    "done": Required[list[ReadResponseConventionsItemsItemRef]],
    "observed": list[ReadResponseConventionsItemsItemRef],
    "observed_truncated": bool,
    "observed_page": ReadResponseStateOfRecord1ObservedPage,
    "relationships_truncated": bool,
    "depends_on": Required[list[DependencyRef1 | DependencyRef2 | DependencyRef3]],
    "invalidated_by": Required[list[str]],
}, total=False)

ReadResponseReceiptsItem = TypedDict("ReadResponseReceiptsItem", {
    "scope": Required[DependencyRef1Scope],
    "receipt_id": Required[str],
}, total=False)

ReadResponse = TypedDict("ReadResponse", {
    "conventions": ReadResponseConventions,
    "schema": Required[Literal["nuryel.state.read/1"]],
    "receipt_id": Required[str],
    "scope": Required[DependencyRef1Scope],
    "state_of_record": Required[ReadResponseStateOfRecord1 | None],
    "denied_scopes": Required[list[DependencyRef1Scope]],
    "records": dict[str, dict[str, Any]],
    "scopes": list[DependencyRef1Scope],
    "receipts": list[ReadResponseReceiptsItem],
    "envelope": Required[dict[str, Any]],
}, total=False)

SubscribeResponseEventsItem = TypedDict("SubscribeResponseEventsItem", {
    "visibility": ActionReceiptVisibility,
    "schema": Required[Literal["nuryel.state.subscribe/1"]],
    "seq": Required[int],
    "at": Required[str],
    "scope": Required[DependencyRef1Scope],
    "facet": Required[Literal["decisions", "constraints", "bugs", "findings", "receipts", "commitments", "derived", "entities", "relationships", "conventions"]],
    "record_id": Required[str],
    "record_hash": Required[str],
    "change": Required[Literal["created", "updated", "superseded", "retired", "invalidated"]],
    "subject": str,
    "invalidates": Required[list[str]],
    "cause": ChangeEventCause1 | DependencyRef2 | ChangeEventCause3,
}, total=False)

SubscribeResponse = TypedDict("SubscribeResponse", {
    "schema": Required[Literal["nuryel.state.subscribe/1"]],
    "scope": Required[DependencyRef1Scope],
    "head_seq": Required[int],
    "events": Required[list[SubscribeResponseEventsItem]],
    "filtered": Required[bool],
    "floor_seq": Required[int],
    "resync": Required[bool],
}, total=False)

CapabilitiesResponsePrincipal = TypedDict("CapabilitiesResponsePrincipal", {
    "id": Required[str],
    "kind": Required[Literal["human", "agent", "service"]],
    "grants": Required[list[DependencyRef1Scope]],
}, total=False)

CapabilitiesResponse = TypedDict("CapabilitiesResponse", {
    "protocol": Required[Literal["nuryel.state/1"]],
    "capabilities": Required[list[str]],
    "repository": Required[DependencyRef1Scope],
    "partitions": Required[list[Literal["organization", "team", "user", "repository"]]],
    "principal": Required[CapabilitiesResponsePrincipal],
}, total=False)

HealthResponse = TypedDict("HealthResponse", {
    "ok": Required[bool],
    "version": Required[str],
    "protocol": Required[Literal["nuryel.state/1"]],
    "partitions": list[str],
}, total=False)

StateProblemConflict = TypedDict("StateProblemConflict", {
    "incumbent_id": Required[str],
    "reason": Required[str],
}, total=False)

StateProblem = TypedDict("StateProblem", {
    "type": Required[str],
    "title": Required[str],
    "status": Required[int],
    "detail": Required[str],
    "conflict": StateProblemConflict,
    "issues": list[str],
}, total=False)
